trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: PushWBCodeBotToDocker
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.17.1'
    displayName: 'Install Node.js'

  - task: Npm@1
    displayName: 'Install NPM'

  - task: Docker@2
    inputs:
      repository: '$(DOCKER_IMAGE_NAME)'
      command: 'login'
      arguments: '-u "$(DOCKER_USERNAME)" --password-stdin "$(DOCKER_REGISTRY)"'
    displayName: 'Docker Login'
    env:
      DOCKER_REGISTRY: '$(DOCKER_REGISTRY)'
      DOCKER_USERNAME: '$(DOCKER_USERNAME)'
      DOCKER_PASSWORD: '$(DOCKER_PASSWORD)'

  - task: Docker@2
    inputs:
      containerRegistry: '$(DOCKER_REGISTRY)'
      repository: '$(DOCKER_IMAGE_NAME)'
      command: 'build'
      arguments: '-t "$(DOCKER_REGISTRY)/$(DOCKER_IMAGE_NAME)" .'
    displayName: 'Build Docker Image'
    env:
      DOCKER_REGISTRY: '$(DOCKER_REGISTRY)'
      DOCKER_IMAGE_NAME: '$(DOCKER_IMAGE_NAME)'

  - task: Docker@2
    inputs:
      containerRegistry: '$(DOCKER_REGISTRY)'
      repository: '$(DOCKER_IMAGE_NAME)'
      command: 'push'
      arguments: '"$(DOCKER_REGISTRY)/$(DOCKER_IMAGE_NAME)"'
    displayName: 'Push Docker Image'
    env:
      DOCKER_REGISTRY: '$(DOCKER_REGISTRY)'
      DOCKER_IMAGE_NAME: '$(DOCKER_IMAGE_NAME)'
