trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: PushWBCodeBotToDocker
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.17.1'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install NPM'

  - script: |
      echo "$(DOCKER_PASSWORD)" | docker login -u "$(DOCKER_USERNAME)" --password-stdin "$(DOCKER_REGISTRY)"
    displayName: 'Docker Login'
    env:
      DOCKER_REGISTRY: '$(DOCKER_REGISTRY)'
      DOCKER_USERNAME: '$(DOCKER_USERNAME)'
      DOCKER_PASSWORD: '$(DOCKER_PASSWORD)'

  - script: |
      docker build -t "$(DOCKER_USERNAME)/$(DOCKER_IMAGE_NAME)" .
    displayName: 'Build Docker Image'
    env:
      DOCKER_USERNAME: '$(DOCKER_USERNAME)'
      DOCKER_IMAGE_NAME: '$(DOCKER_IMAGE_NAME)'

  - script: |
      docker tag "$(DOCKER_USERNAME)/$(DOCKER_IMAGE_NAME)" $(VM_IP)/$(DOCKER_USERNAME)/$(DOCKER_IMAGE_NAME)
      docker push $(VM_IP)/$(DOCKER_USERNAME)/$(DOCKER_IMAGE_NAME)
    displayName: 'Push Docker Image to VM'
    env:
      DOCKER_IMAGE_NAME: '$(DOCKER_IMAGE_NAME)'
      VM_IP: '$(VM_IP)'
      DOCKER_USERNAME: '$(DOCKER_USERNAME)'
