trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: RunDiscordBot
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      export GITHUB_CLIENT_ID=$(CLIENT_ID)
      export GITHUB_CLIENT_TOKEN=$(CLIENT_TOKEN)
      node wbc_main_bot.js
    displayName: 'Run Discord Bot'
    env:
      CLIENT_ID: $(GITHUB_CLIENT_ID)
      CLIENT_TOKEN: $(GITHUB_CLIENT_TOKEN)
