trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: PushWBCodeBotToDocker
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.17.1'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Run Discord Bot'

  - script: |
      echo "$(docker_password)" | docker login -u "$(docker_username)" --password-stdin "$(docker_registry)"
    displayName: 'Docker Login'
    env:
      DOCKER_REGISTRY: 'docker_registry'
      DOCKER_USERNAME: 'docker_username'
      DOCKER_PASSWORD: 'docker_password'

  - script: |
      docker build -t "$(docker_image_name)" .
    displayName: 'Build Docker Image'
    env:
      DOCKER_IMAGE_NAME: 'docker_image_name'

  - script: |
      docker push "$(docker_registry)/$(docker_image_name)"
    displayName: 'Push Docker Image'
