trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DeployWBCodesBot
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.17.1'
    displayName: 'Install Node.js'

  - script: |
      npm install
      node wbc_main_bot.js
    displayName: 'Run Discord Bot'
    env:
      CLIENT_ID: $(CLIENT_ID)
      CLIENT_TOKEN: $(CLIENT_TOKEN)
